name: 📚 Documentation
description: Report documentation issues or suggest improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please provide details about the documentation issue or improvement.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is affected?
      options:
        - Getting Started Guide
        - API Reference
        - User Guide
        - Developer Guide
        - Troubleshooting
        - Security Documentation
        - README
        - Other
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the documentation issue or improvement needed.
      placeholder: What's wrong with the documentation or what improvement do you suggest?
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: If reporting an issue, paste the current documentation content that needs fixing.
      placeholder: Paste the current documentation content here...

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix/Improvement
      description: If you have a suggestion for how to fix or improve the documentation, please provide it here.
      placeholder: Describe how you think the documentation should be improved...

  - type: input
    id: page-url
    attributes:
      label: Page URL
      description: If applicable, provide the URL or path to the documentation page.
      placeholder: https://docs.osmynt.com/...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context about the documentation issue or improvement.
      placeholder: Any other information that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I have searched for existing issues before creating this one
          required: true
        - label: I have provided all the requested information
          required: true
