export const TEAMS_AUDIT_LOG_ACTIONS = {
	TEAM_CREATED_DEFAULT: "TEAM_CREATED_DEFAULT",
	TEAM_MEMBER_CREATED_DEFAULT: "TEAM_MEMBER_CREATED_DEFAULT",
	TEAM_MEMBER_ACCEPTED_INVITATION: "TEAM_MEMBER_ACCEPTED_INVITATION",
	TEAM_MEMBER_REMOVED: "TEAM_MEMBER_REMOVED",
	TEAM_INVITATION_CREATED: "TEAM_INVITATION_CREATED",
	TEAM_INVITATION_ACCEPTED: "TEAM_INVITATION_ACCEPTED",
};
