# GitHub Pages Configuration for Osmynt Documentation

# Site settings
title: Osmynt Documentation
description: "Secure, Git-powered, Realtime DM for code blocks ⚡"
url: "https://docs.osmynt.dev"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins (automatically included with github-pages gem)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
author: Moeen Mahmud
twitter:
  username: moeen_mahmud
  card: summary_large_image

# Navigation
navigation:
  - title: Getting Started
    url: /getting-started/
  - title: Features
    url: /features/
  - title: Reference
    url: /reference/
  - title: Troubleshooting
    url: /troubleshooting/
  - title: Security
    url: /security/
  - title: Resources
    url: /resources/

# Collections
collections:
  getting-started:
    output: true
    permalink: /:name/
  features:
    output: true
    permalink: /:name/
  reference:
    output: true
    permalink: /:name/
  troubleshooting:
    output: true
    permalink: /:name/
  security:
    output: true
    permalink: /:name/
  resources:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "getting-started"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "features"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "reference"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "troubleshooting"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "security"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
